project:
  type: website
  output-dir: _site

website:
  title: "Aprendizaje Maquina Estadístico"
  site-url: https://angelaortiz25.github.io/aprendizaje_maquina_estadistico/

format:
  html:
    theme: cosmo
    toc: true