project:
  type: website

website:
  title: "Aprendizaje Maquina Estadístico"
  navbar:
    right:
      - icon: github
        href: https://github.com/AngelaOrtiz25/aprendizaje_maquina_estadistico.git

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  echo: true
  warning: false
  message: false

jupyter: julia-1.11