project:
  type: website

website:
  title: "Aprendizaje Máquina Estadístico"
  navbar:
    left:
      - href: index.qmd
        text: "Inicio"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css